name : TestPilot AI CI-PipeLine

on:
  push:
     branches: [main]
  pull_request:   
     branches: [main]
  schedule:
   - cron: '30 3 * * *'  # Runs daily at 9AM IST   


jobs:
  ui-tests:
    name: Playwright UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: web-tests
        run: npm ci

      - name: Install Playwright browsers
        working-directory: web-tests
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: web-tests
        run: npx playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: web-tests/playwright-report/



  api-tests:
    name: RestAssured API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run API tests
        working-directory: api-tests
        run: mvn test

      - name: Upload API test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: api-tests/target/surefire-reports/          